language: node_js

node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=1895723ee201038cd53669d9757beb6a18e64f89e7b47f5149e7bb3e6fae7aa7

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run bootstrap

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:  false
